package sfmc.beerorders.domain;

public enum BeerOrderStatus {
    NEW, PENDING_VALIDATION, VALIDATED, VALIDATION_EXCEPTION,
    PENDING_ALLOCATION, ALLOCATED, ALLOCATION_EXCEPTION,
    PENDING_INVENTORY, PICKED_UP, CANCELED
}
