package sfmc.beerorders.domain;

public enum BeerOrderEvent {
    VALIDATION, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATION, ALLOCATION_SUCCESS, ALLOCATION_FAILED, ALLOCATION_NO_INVENTORY,
    BEER_ORDER_PICKED_UP, CANCEL_ORDER
}
