package sfmc.beerorders.domain;

public enum BeerOrderStatus {
    NEW, VALIDATED, VALIDATION_EXCEPTION, ALLOCATED, ALLOCATION_EXCEPTION,
    PENDING_INVENTORY, PICKED_UP, DELIVERY, DELIVERY_EXCEPTION
}
